title: Mykhalevych
email: taras.mykhalevych@gmail.com
author: Taras Mykhalevych
description: Here you are, it's my blog, and you are welcome here! 🙂
baseurl: "/"
url: "https://tmykha.com"
github_username: tmykhalevych

theme: jekyll-theme-clean-blog

paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
